---
version: "3"
tasks:
  build:
    sources:
      - src/**.zig
      - ./build.zig
      - ./build.zig.zon
    generates:
      - ./zig-out/bin/todo_zen
    cmds:
      - zig build --release=fast install
  install:
    deps:
      - build
    cmds:
      - for:
          - prompt
          - rprompt
          - session
          - transient
          - status
        cmd: mv ./zig-out/bin/stoa-{{.ITEM}} ~/.local/bin/
